### ISSUE TITLE
Does not actually install MySQL with the newer versions of the installer.

### ISSUE THREAD

**Issue by kusuriya** [PowerShell/xMySql#1]
The newer versions of the MySQL installer are in a different location "$env:programfiles(x86)\MySQL Installer for windows" and have a whole different set of command line options that make this module non functioning.

**Comment by TravisEz13** [comment]
I've verified this is an issue

**Comment by TravisEz13** [comment]
I Tested an intermediate release and in addition it doesn't work because MySql changed the package name and ProductID
http://dev.mysql.com/get/Downloads/MySQLInstaller/mysql-installer-community-5.6.24.0.msi

**Comment by kusuriya** [comment]
Even changing that in the module it will install the installer and not actually install the MySQL server.

**Comment by NarineM** [comment]
#8  changes contain a fix for this issue as well. Closing this one.
