### ISSUE TITLE
BLOCKER: PSSA Errors and Newlines at End of Files Need to Be Fixed

### ISSUE THREAD

**Issue by kwirkykat** [PowerShell/xMySql#15]
Errors from PS script analyzer and the absence of newlines at the end of every file are causing the tests to fail like [this](https://ci.appveyor.com/project/PowerShell/xmysql/build/2.1.52.0).
This resource module cannot be released until these errors are fixed or suppressed and the tests are passing.

**Comment by Indhukrishna** [comment]
#14
