### ISSUE TITLE
Security: Traces password on DscResources/MSFT_xMySqlDatabase/MSFT_xMySqlDatabase.psm1  line 39

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/xMySql#4]
Traces password on DscResources/MSFT_xMySqlDatabase/MSFT_xMySqlDatabase.psm1  line 39
Also on xMySql/DscResources/MSFT_xMySqlUser/MSFT_xMySqlUser.psm1 line 34

**Comment by tysonjhayes** [comment]
Removed traces of passwords in current dev instance.
